// Generated by CoffeeScript 1.9.2
var GeneralIcon, greenIcon, layer, map, oReq, reqListener, skullIcon, start, url;

start = [40.6294862, -74.022639];

layer = new L.StamenTileLayer("toner-lite", {
  attribution: "Map tiles by <a href=\"http://stamen.com\">Stamen Design</a>, under <a href=\"http://creativecommons.org/licenses/by/3.0\">CC BY 3.0</a>. Data by <a href=\"http://openstreetmap.org\">OpenStreetMap</a>, under <a href=\"http://www.openstreetmap.org/copyright\">ODbL</a>."
});

map = new L.Map("map", {
  center: new L.LatLng(start[0], start[1]),
  zoom: 12
});

map.addLayer(layer);

greenIcon = L.icon({
  iconUrl: 'leaf-orange.png',
  shadowUrl: 'leaf-shadow.png',
  iconSize: [38, 95],
  shadowSize: [50, 64],
  iconAnchor: [22, 94],
  shadowAnchor: [4, 62],
  popupAnchor: [-3, -76]
});

L.marker(start, {
  icon: greenIcon
}).addTo(map);

GeneralIcon = L.Icon.extend({
  options: {
    shadowUrl: 'skull_shadow.png',
    iconSize: [80, 106],
    shadowSize: [143, 112],
    iconAnchor: [40, 106],
    shadowAnchor: [10, 112],
    popupAnchor: [-3, -76]
  }
});

skullIcon = new GeneralIcon({
  iconUrl: 'skull_small.png'
});

reqListener = function() {
  var data, i, j, len, results, x;
  data = JSON.parse(this.responseText);
  results = [];
  for (i = j = 0, len = data.length; j < len; i = ++j) {
    x = data[i];
    results.push(L.marker([x.lat, x.long], {
      icon: skullIcon,
      clickable: false,
      opacity: 0.8
    }).addTo(map));
  }
  return results;
};

url = "motor_related_deaths.json";

oReq = new XMLHttpRequest();

oReq.addEventListener('load', reqListener);

oReq.open("get", url, true);

oReq.send();

//# sourceMappingURL=script.js.map
