// Generated by CoffeeScript 1.9.2
var layer, map, markers, oReq, reqListener, small_skull, start, tiny_skull, url;

start = [40.6294862, -74.022639];

layer = new L.StamenTileLayer("toner-lite", {
  attribution: "Map tiles by <a href=\"http://stamen.com\">Stamen Design</a>, under <a href=\"http://creativecommons.org/licenses/by/3.0\">CC BY 3.0</a>. Data by <a href=\"http://openstreetmap.org\">OpenStreetMap</a>, under <a href=\"http://www.openstreetmap.org/copyright\">ODbL</a>."
});

map = new L.Map("map", {
  center: new L.LatLng(start[0], start[1]),
  zoom: 13
});

map.addLayer(layer);

map.on('zoomend', function() {
  var currentZoom, j, k, len, len1, marker, results;
  currentZoom = map.getZoom();
  console.log(currentZoom);
  if (currentZoom <= 12) {
    for (j = 0, len = markers.length; j < len; j++) {
      marker = markers[j];
      marker.setIcon(tiny_skull);
    }
  }
  if (currentZoom > 12) {
    results = [];
    for (k = 0, len1 = markers.length; k < len1; k++) {
      marker = markers[k];
      results.push(marker.setIcon(small_skull));
    }
    return results;
  }
});

small_skull = L.icon({
  iconUrl: 'small_skull.png',
  shadowUrl: 'small_skull_shadow.png',
  iconSize: [80, 106],
  shadowSize: [143, 112],
  iconAnchor: [40, 106],
  shadowAnchor: [10, 112],
  popupAnchor: [-3, -76]
});

tiny_skull = L.icon({
  iconUrl: 'small_skull.png',
  shadowUrl: 'small_skull_shadow.png',
  iconSize: [40, 53],
  shadowSize: [121, 56],
  iconAnchor: [20, 53],
  shadowAnchor: [5, 56],
  popupAnchor: [-3, -76]
});

markers = [];

reqListener = function() {
  var data, i, j, len, results, x;
  data = JSON.parse(this.responseText);
  results = [];
  for (i = j = 0, len = data.length; j < len; i = ++j) {
    x = data[i];
    results.push(markers.push(L.marker([x.lat, x.long], {
      icon: small_skull,
      clickable: false,
      opacity: 0.8
    }).addTo(map)));
  }
  return results;
};

url = "motor_related_deaths.json";

oReq = new XMLHttpRequest();

oReq.addEventListener('load', reqListener);

oReq.open("get", url, true);

oReq.send();

//# sourceMappingURL=script.js.map
